const fs = require('fs');
const p = 'src-tauri/src/services/provider/mod.rs';
let t = fs.readFileSync(p, 'utf8');
let n = 0;
t = t.replace(/([ \t]*)let mut backfill_completed = false;\r?\n/, (m) => { n++; return ''; });
t = t.replace(/[ \t]*backfill_completed = true;\r?\n/g, (m) => { n++; return ''; });
t = t.replace(/([ \t]*)let mut backfill_completed = false;\n/, (m) => { n++; return ''; });
t = t.replace(/[ \t]*backfill_completed = true;\n/g, (m) => { n++; return ''; });
fs.writeFileSync(p, t);
console.log('removed', n);
